# Generated by Django 2.2 on 2019-04-15 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_tweet', to='core.Tweet')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_timeline', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_tweet', to='core.Tweet')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_timeline', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
